using WindowsInitializer.Contracts;

namespace WindowsInitializer.App;

internal static class CatalogLocalization
{
    private static readonly string[] RegistryDomainNames = ["Desktop and Explorer", "Privacy and notifications", "Power and shutdown", "Windows Update", "Cloud content and Edge", "Gaming and multimedia", "Network and remote access", "Security and setup", "Context menu tools", "Performance and file system", "Developer and terminal", "Other registry settings"];
    private static readonly IReadOnlyDictionary<string, string[]> RegistryDomains = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase)
    {
        ["zh-CN"] = ["桌面与资源管理器", "隐私与通知", "电源与关机", "Windows 更新", "云内容与 Edge", "游戏与多媒体", "网络与远程访问", "安全与安装", "右键菜单工具", "性能与文件系统", "开发者与终端", "其他注册表设置"],
        ["ru"] = ["Рабочий стол и Проводник", "Конфиденциальность и уведомления", "Питание и завершение работы", "Центр обновления Windows", "Облачный контент и Edge", "Игры и мультимедиа", "Сеть и удаленный доступ", "Безопасность и установка", "Контекстное меню", "Производительность и файловая система", "Разработка и терминал", "Другие параметры реестра"],
        ["es"] = ["Escritorio y Explorador", "Privacidad y notificaciones", "Energía y apagado", "Windows Update", "Contenido en la nube y Edge", "Juegos y multimedia", "Red y acceso remoto", "Seguridad e instalación", "Menú contextual", "Rendimiento y sistema de archivos", "Desarrollo y terminal", "Otros ajustes del registro"],
        ["fr"] = ["Bureau et Explorateur", "Confidentialité et notifications", "Alimentation et arrêt", "Windows Update", "Contenu cloud et Edge", "Jeux et multimédia", "Réseau et accès distant", "Sécurité et installation", "Menu contextuel", "Performances et système de fichiers", "Développement et terminal", "Autres paramètres du Registre"],
        ["ar"] = ["سطح المكتب ومستكشف الملفات", "الخصوصية والإشعارات", "الطاقة وإيقاف التشغيل", "Windows Update", "المحتوى السحابي وEdge", "الألعاب والوسائط", "الشبكة والوصول عن بعد", "الأمان والإعداد", "أدوات قائمة السياق", "الأداء ونظام الملفات", "التطوير والطرفية", "إعدادات سجل أخرى"],
        ["pt-BR"] = ["Área de trabalho e Explorador", "Privacidade e notificações", "Energia e desligamento", "Windows Update", "Conteúdo na nuvem e Edge", "Jogos e multimídia", "Rede e acesso remoto", "Segurança e instalação", "Menu de contexto", "Desempenho e sistema de arquivos", "Desenvolvimento e terminal", "Outras configurações do Registro"],
        ["ja"] = ["デスクトップとエクスプローラー", "プライバシーと通知", "電源とシャットダウン", "Windows Update", "クラウド コンテンツと Edge", "ゲームとマルチメディア", "ネットワークとリモート アクセス", "セキュリティとセットアップ", "コンテキスト メニュー", "パフォーマンスとファイル システム", "開発者とターミナル", "その他のレジストリ設定"],
        ["de"] = ["Desktop und Explorer", "Datenschutz und Benachrichtigungen", "Energie und Herunterfahren", "Windows Update", "Cloudinhalte und Edge", "Spiele und Multimedia", "Netzwerk und Fernzugriff", "Sicherheit und Einrichtung", "Kontextmenü-Werkzeuge", "Leistung und Dateisystem", "Entwicklung und Terminal", "Weitere Registrierungseinstellungen"]
    };
    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Domains =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["zh-CN"] = Map(("Device and accounts", "设备与账户"), ("Language and display", "语言与显示"), ("Runtime", "运行库"), ("Applications", "应用"), ("Browsers", "浏览器"), ("Development tools", "开发工具"), ("Graphics and media", "图形与媒体"), ("Package managers", "包管理器"), ("Utilities", "实用工具"), ("Networking", "网络工具"), ("Network", "网络工具"), ("Virtualization", "虚拟化"), ("Mobile tools", "移动工具"), ("System utilities", "系统工具"), ("Offline and legacy", "离线与旧版工具"), ("Security", "安全"), ("Security and system", "安全与系统")),
            ["ru"] = Map(("Device and accounts", "Устройство и учетные записи"), ("Language and display", "Язык и экран"), ("Runtime", "Среды выполнения"), ("Applications", "Приложения"), ("Browsers", "Браузеры"), ("Development tools", "Инструменты разработки"), ("Graphics and media", "Графика и мультимедиа"), ("Package managers", "Менеджеры пакетов"), ("Utilities", "Утилиты"), ("Networking", "Сетевые инструменты"), ("Network", "Сетевые инструменты"), ("Virtualization", "Виртуализация"), ("Mobile tools", "Мобильные инструменты"), ("System utilities", "Системные утилиты"), ("Offline and legacy", "Автономные и устаревшие"), ("Security", "Безопасность"), ("Security and system", "Безопасность и система")),
            ["es"] = Map(("Device and accounts", "Dispositivo y cuentas"), ("Language and display", "Idioma y pantalla"), ("Runtime", "Entornos de ejecución"), ("Applications", "Aplicaciones"), ("Browsers", "Navegadores"), ("Development tools", "Herramientas de desarrollo"), ("Graphics and media", "Gráficos y multimedia"), ("Package managers", "Gestores de paquetes"), ("Utilities", "Utilidades"), ("Networking", "Herramientas de red"), ("Network", "Herramientas de red"), ("Virtualization", "Virtualización"), ("Mobile tools", "Herramientas móviles"), ("System utilities", "Utilidades del sistema"), ("Offline and legacy", "Sin conexión y heredado"), ("Security", "Seguridad"), ("Security and system", "Seguridad y sistema")),
            ["fr"] = Map(("Device and accounts", "Appareil et comptes"), ("Language and display", "Langue et affichage"), ("Runtime", "Environnements d’exécution"), ("Applications", "Applications"), ("Browsers", "Navigateurs"), ("Development tools", "Outils de développement"), ("Graphics and media", "Graphisme et multimédia"), ("Package managers", "Gestionnaires de paquets"), ("Utilities", "Utilitaires"), ("Networking", "Outils réseau"), ("Network", "Outils réseau"), ("Virtualization", "Virtualisation"), ("Mobile tools", "Outils mobiles"), ("System utilities", "Utilitaires système"), ("Offline and legacy", "Hors ligne et ancien"), ("Security", "Sécurité"), ("Security and system", "Sécurité et système")),
            ["ar"] = Map(("Device and accounts", "الجهاز والحسابات"), ("Language and display", "اللغة والعرض"), ("Runtime", "بيئات التشغيل"), ("Applications", "التطبيقات"), ("Browsers", "المتصفحات"), ("Development tools", "أدوات التطوير"), ("Graphics and media", "الرسومات والوسائط"), ("Package managers", "مديرو الحزم"), ("Utilities", "الأدوات المساعدة"), ("Networking", "أدوات الشبكة"), ("Network", "أدوات الشبكة"), ("Virtualization", "المحاكاة الافتراضية"), ("Mobile tools", "أدوات الهاتف"), ("System utilities", "أدوات النظام"), ("Offline and legacy", "دون اتصال وقديم"), ("Security", "الأمان"), ("Security and system", "الأمان والنظام")),
            ["pt-BR"] = Map(("Device and accounts", "Dispositivo e contas"), ("Language and display", "Idioma e tela"), ("Runtime", "Ambientes de execução"), ("Applications", "Aplicativos"), ("Browsers", "Navegadores"), ("Development tools", "Ferramentas de desenvolvimento"), ("Graphics and media", "Gráficos e mídia"), ("Package managers", "Gerenciadores de pacotes"), ("Utilities", "Utilitários"), ("Networking", "Ferramentas de rede"), ("Network", "Ferramentas de rede"), ("Virtualization", "Virtualização"), ("Mobile tools", "Ferramentas móveis"), ("System utilities", "Utilitários do sistema"), ("Offline and legacy", "Offline e legado"), ("Security", "Segurança"), ("Security and system", "Segurança e sistema")),
            ["ja"] = Map(("Device and accounts", "デバイスとアカウント"), ("Language and display", "言語と表示"), ("Runtime", "ランタイム"), ("Applications", "アプリ"), ("Browsers", "ブラウザー"), ("Development tools", "開発ツール"), ("Graphics and media", "グラフィックスとメディア"), ("Package managers", "パッケージ マネージャー"), ("Utilities", "ユーティリティ"), ("Networking", "ネットワーク ツール"), ("Network", "ネットワーク ツール"), ("Virtualization", "仮想化"), ("Mobile tools", "モバイル ツール"), ("System utilities", "システム ユーティリティ"), ("Offline and legacy", "オフラインとレガシー"), ("Security", "セキュリティ"), ("Security and system", "セキュリティとシステム")),
            ["de"] = Map(("Device and accounts", "Gerät und Konten"), ("Language and display", "Sprache und Anzeige"), ("Runtime", "Laufzeitumgebungen"), ("Applications", "Anwendungen"), ("Browsers", "Browser"), ("Development tools", "Entwicklungswerkzeuge"), ("Graphics and media", "Grafik und Medien"), ("Package managers", "Paketmanager"), ("Utilities", "Dienstprogramme"), ("Networking", "Netzwerkwerkzeuge"), ("Network", "Netzwerkwerkzeuge"), ("Virtualization", "Virtualisierung"), ("Mobile tools", "Mobile Werkzeuge"), ("System utilities", "Systemprogramme"), ("Offline and legacy", "Offline und Legacy"), ("Security", "Sicherheit"), ("Security and system", "Sicherheit und System"))
        };

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> TaskNames =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["zh-CN"] = Map(("computer-name", "Windows 计算机名称"), ("accounts-local", "本地账户"), ("language-zh-cn", "中文（简体，中国）"), ("language-zh-tw", "中文（繁体，台湾）"), ("language-en-us", "英语（美国）"), ("language-en-gb", "英语（英国）"), ("language-zh-sg", "中文（新加坡）区域格式"), ("language-zh-hk", "中文（香港）区域格式"), ("language-ui-preference", "Windows 显示语言首选项"), ("font-supplements-cjk-indic-europe", "补充字体"), ("feature-wireless-display", "无线显示器"), ("device-setup-region", "设备设置区域"), ("legacy-god-mode", "创建 Windows 上帝模式文件夹")),
            ["ru"] = Map(("computer-name", "Имя компьютера Windows"), ("accounts-local", "Локальные учетные записи"), ("language-zh-cn", "Китайский (упрощенный, Китай)"), ("language-zh-tw", "Китайский (традиционный, Тайвань)"), ("language-en-us", "Английский (США)"), ("language-en-gb", "Английский (Великобритания)"), ("language-zh-sg", "Китайский (Сингапур), региональный формат"), ("language-zh-hk", "Китайский (Гонконг), региональный формат"), ("language-ui-preference", "Язык интерфейса Windows"), ("font-supplements-cjk-indic-europe", "Дополнительные шрифты"), ("feature-wireless-display", "Беспроводной дисплей"), ("device-setup-region", "Регион настройки устройства"), ("legacy-god-mode", "Создать папку Windows God Mode")),
            ["es"] = Map(("computer-name", "Nombre del equipo Windows"), ("accounts-local", "Cuentas locales"), ("language-zh-cn", "Chino (simplificado, China)"), ("language-zh-tw", "Chino (tradicional, Taiwán)"), ("language-en-us", "Inglés (Estados Unidos)"), ("language-en-gb", "Inglés (Reino Unido)"), ("language-zh-sg", "Formato regional chino (Singapur)"), ("language-zh-hk", "Formato regional chino (Hong Kong)"), ("language-ui-preference", "Idioma de pantalla de Windows"), ("font-supplements-cjk-indic-europe", "Fuentes complementarias"), ("feature-wireless-display", "Pantalla inalámbrica"), ("device-setup-region", "Región de configuración del dispositivo"), ("legacy-god-mode", "Crear carpeta Modo Dios de Windows")),
            ["fr"] = Map(("computer-name", "Nom de l’ordinateur Windows"), ("accounts-local", "Comptes locaux"), ("language-zh-cn", "Chinois (simplifié, Chine)"), ("language-zh-tw", "Chinois (traditionnel, Taïwan)"), ("language-en-us", "Anglais (États-Unis)"), ("language-en-gb", "Anglais (Royaume-Uni)"), ("language-zh-sg", "Format régional chinois (Singapour)"), ("language-zh-hk", "Format régional chinois (Hong Kong)"), ("language-ui-preference", "Langue d’affichage de Windows"), ("font-supplements-cjk-indic-europe", "Polices supplémentaires"), ("feature-wireless-display", "Affichage sans fil"), ("device-setup-region", "Région de configuration de l’appareil"), ("legacy-god-mode", "Créer le dossier Mode Dieu de Windows")),
            ["ar"] = Map(("computer-name", "اسم كمبيوتر Windows"), ("accounts-local", "الحسابات المحلية"), ("language-zh-cn", "الصينية (المبسطة، الصين)"), ("language-zh-tw", "الصينية (التقليدية، تايوان)"), ("language-en-us", "الإنجليزية (الولايات المتحدة)"), ("language-en-gb", "الإنجليزية (المملكة المتحدة)"), ("language-zh-sg", "تنسيق الصينية الإقليمي (سنغافورة)"), ("language-zh-hk", "تنسيق الصينية الإقليمي (هونغ كونغ)"), ("language-ui-preference", "لغة عرض Windows"), ("font-supplements-cjk-indic-europe", "خطوط إضافية"), ("feature-wireless-display", "العرض اللاسلكي"), ("device-setup-region", "منطقة إعداد الجهاز"), ("legacy-god-mode", "إنشاء مجلد وضع الإله في Windows")),
            ["pt-BR"] = Map(("computer-name", "Nome do computador Windows"), ("accounts-local", "Contas locais"), ("language-zh-cn", "Chinês (simplificado, China)"), ("language-zh-tw", "Chinês (tradicional, Taiwan)"), ("language-en-us", "Inglês (Estados Unidos)"), ("language-en-gb", "Inglês (Reino Unido)"), ("language-zh-sg", "Formato regional chinês (Singapura)"), ("language-zh-hk", "Formato regional chinês (Hong Kong)"), ("language-ui-preference", "Idioma de exibição do Windows"), ("font-supplements-cjk-indic-europe", "Fontes complementares"), ("feature-wireless-display", "Vídeo sem fio"), ("device-setup-region", "Região de configuração do dispositivo"), ("legacy-god-mode", "Criar pasta Modo Deus do Windows")),
            ["ja"] = Map(("computer-name", "Windows コンピューター名"), ("accounts-local", "ローカル アカウント"), ("language-zh-cn", "中国語（簡体字、中国）"), ("language-zh-tw", "中国語（繁体字、台湾）"), ("language-en-us", "英語（米国）"), ("language-en-gb", "英語（英国）"), ("language-zh-sg", "中国語（シンガポール）の地域形式"), ("language-zh-hk", "中国語（香港）の地域形式"), ("language-ui-preference", "Windows の表示言語"), ("font-supplements-cjk-indic-europe", "補助フォント"), ("feature-wireless-display", "ワイヤレス ディスプレイ"), ("device-setup-region", "デバイスのセットアップ地域"), ("legacy-god-mode", "Windows God Mode フォルダーを作成")),
            ["de"] = Map(("computer-name", "Windows-Computername"), ("accounts-local", "Lokale Konten"), ("language-zh-cn", "Chinesisch (vereinfacht, China)"), ("language-zh-tw", "Chinesisch (traditionell, Taiwan)"), ("language-en-us", "Englisch (Vereinigte Staaten)"), ("language-en-gb", "Englisch (Vereinigtes Königreich)"), ("language-zh-sg", "Chinesisches Regionalformat (Singapur)"), ("language-zh-hk", "Chinesisches Regionalformat (Hongkong)"), ("language-ui-preference", "Windows-Anzeigesprache"), ("font-supplements-cjk-indic-europe", "Zusätzliche Schriftarten"), ("feature-wireless-display", "Drahtlose Anzeige"), ("device-setup-region", "Region für die Geräteeinrichtung"), ("legacy-god-mode", "Windows-God-Mode-Ordner erstellen"))
        };

    private static readonly string[] V23TaskIds =
    [
        "feature-wsl", "feature-virtual-machine-platform", "feature-sandbox", "feature-hyper-v", "capability-openssh-client",
        "feature-telnet-client", "setting-long-paths", "setting-developer-mode", "setting-show-file-extensions",
        "setting-hibernation", "setting-fast-startup", "safety-restore-point", "setting-windows-update-mode",
        "setting-power-plan", "setting-sleep-timeouts"
    ];

    private static readonly IReadOnlyDictionary<string, string[]> V23TaskNames = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase)
    {
        ["zh-CN"] = ["适用于 Linux 的 Windows 子系统", "虚拟机平台", "Windows 沙盒", "Hyper-V", "OpenSSH 客户端", "Telnet 客户端", "长路径支持", "开发者模式", "显示文件扩展名", "启用休眠", "启用快速启动", "创建系统还原点", "Windows 更新模式", "活动电源计划", "睡眠与屏幕超时"],
        ["ru"] = ["Подсистема Windows для Linux", "Платформа виртуальных машин", "Песочница Windows", "Hyper-V", "Клиент OpenSSH", "Клиент Telnet", "Поддержка длинных путей", "Режим разработчика", "Показывать расширения файлов", "Включить гибернацию", "Включить быстрый запуск", "Создать точку восстановления", "Режим Центра обновления Windows", "Активная схема питания", "Тайм-ауты сна и экрана"],
        ["es"] = ["Subsistema de Windows para Linux", "Plataforma de máquina virtual", "Espacio aislado de Windows", "Hyper-V", "Cliente OpenSSH", "Cliente Telnet", "Compatibilidad con rutas largas", "Modo de desarrollador", "Mostrar extensiones de archivo", "Activar hibernación", "Activar inicio rápido", "Crear punto de restauración", "Modo de Windows Update", "Plan de energía activo", "Tiempos de suspensión y pantalla"],
        ["fr"] = ["Sous-système Windows pour Linux", "Plateforme de machine virtuelle", "Bac à sable Windows", "Hyper-V", "Client OpenSSH", "Client Telnet", "Prise en charge des chemins longs", "Mode développeur", "Afficher les extensions de fichiers", "Activer la mise en veille prolongée", "Activer le démarrage rapide", "Créer un point de restauration", "Mode Windows Update", "Mode d’alimentation actif", "Délais de veille et d’affichage"],
        ["ar"] = ["نظام Windows الفرعي لـ Linux", "منصة الجهاز الظاهري", "وضع الحماية في Windows", "Hyper-V", "عميل OpenSSH", "عميل Telnet", "دعم المسارات الطويلة", "وضع المطور", "إظهار امتدادات الملفات", "تمكين الإسبات", "تمكين بدء التشغيل السريع", "إنشاء نقطة استعادة للنظام", "وضع Windows Update", "خطة الطاقة النشطة", "مهلات السكون والشاشة"],
        ["pt-BR"] = ["Subsistema do Windows para Linux", "Plataforma de Máquina Virtual", "Windows Sandbox", "Hyper-V", "Cliente OpenSSH", "Cliente Telnet", "Suporte a caminhos longos", "Modo de desenvolvedor", "Mostrar extensões de arquivo", "Ativar hibernação", "Ativar inicialização rápida", "Criar ponto de restauração", "Modo do Windows Update", "Plano de energia ativo", "Tempos limite de suspensão e tela"],
        ["ja"] = ["Linux 用 Windows サブシステム", "仮想マシン プラットフォーム", "Windows サンドボックス", "Hyper-V", "OpenSSH クライアント", "Telnet クライアント", "長いパスのサポート", "開発者モード", "ファイル名拡張子を表示", "休止状態を有効化", "高速スタートアップを有効化", "システムの復元ポイントを作成", "Windows Update モード", "有効な電源プラン", "スリープと画面のタイムアウト"],
        ["de"] = ["Windows-Subsystem für Linux", "Plattform für virtuelle Computer", "Windows-Sandbox", "Hyper-V", "OpenSSH-Client", "Telnet-Client", "Unterstützung langer Pfade", "Entwicklermodus", "Dateinamenerweiterungen anzeigen", "Ruhezustand aktivieren", "Schnellstart aktivieren", "Systemwiederherstellungspunkt erstellen", "Windows Update-Modus", "Aktiver Energiesparplan", "Zeitlimits für Standby und Bildschirm"]
    };

    private static readonly string[] RegistryGroupTaskIds =
    [
        "registry-group-user-desktop-start", "registry-group-user-file-explorer", "registry-group-user-screen-saver",
        "registry-group-user-visual-responsiveness", "registry-group-user-mouse", "registry-group-user-focus-assist",
        "registry-group-user-privacy-personalization", "registry-group-user-recommended-content", "registry-group-user-search-privacy",
        "registry-group-user-feedback-onboarding", "registry-group-user-notifications", "registry-group-user-gaming",
        "registry-group-user-terminal", "registry-group-user-developer", "registry-group-system-explorer-policy",
        "registry-group-system-feed-copilot", "registry-group-system-cloud-content", "registry-group-system-edge",
        "registry-group-system-windows-update", "registry-group-system-install-bypass", "registry-group-system-power-core",
        "registry-group-system-power-balanced", "registry-group-system-power-performance", "registry-group-system-power-saver",
        "registry-group-system-power-ultimate", "registry-group-system-performance", "registry-group-system-security",
        "registry-group-system-file-sharing", "registry-group-system-remote-desktop", "registry-group-system-device-guard",
        "registry-group-system-file-system", "registry-group-system-shell", "registry-group-system-telemetry",
        "registry-group-hash-context-menus", "registry-group-take-ownership-menus"
    ];

    private static readonly IReadOnlyDictionary<string, string[]> RegistryGroupTaskNames = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase)
    {
        ["zh-CN"] = ["桌面、任务栏与开始菜单", "文件资源管理器行为", "屏幕保护程序", "视觉效果与桌面响应", "鼠标行为", "专注助手", "隐私与个性化", "推荐与推广内容", "Windows 搜索与云历史", "反馈与初始体验提示", "横幅与锁屏通知", "游戏与 Game Bar", "命令提示符与控制台", "开发者功能", "资源管理器、任务栏与开始菜单策略", "资讯、信息流与 Copilot", "Windows 消费者与云内容", "Microsoft Edge 策略", "Windows Update 与传递优化策略", "Windows 安装要求绕过", "休眠、快速启动与活动电源计划", "平衡电源计划行为", "高性能电源计划行为", "节能电源计划行为", "卓越性能电源计划行为", "系统与游戏性能", "系统安全与 UAC", "管理文件共享", "远程桌面访问", "Device Guard 与推测执行设置", "文件系统与长路径设置", "PowerShell 与命令提示符策略", "遥测服务与计划任务", "文件与文件夹哈希右键菜单", "取得所有权右键菜单"],
        ["ru"] = ["Рабочий стол, панель задач и меню Пуск", "Поведение Проводника", "Экранная заставка", "Визуальные эффекты и отзывчивость", "Поведение мыши", "Фокусировка внимания", "Конфиденциальность и персонализация", "Рекомендуемое и рекламное содержимое", "Поиск Windows и облачная история", "Отзывы и начальная настройка", "Всплывающие уведомления и экран блокировки", "Игры и Game Bar", "Командная строка и консоль", "Функции разработчика", "Политики Проводника, панели задач и меню Пуск", "Новости, каналы и Copilot", "Потребительское и облачное содержимое Windows", "Политики Microsoft Edge", "Политики Windows Update и оптимизации доставки", "Обход требований установки Windows", "Гибернация, быстрый запуск и активный план питания", "Сбалансированный план питания", "План высокой производительности", "Энергосберегающий план", "План максимальной производительности", "Производительность системы и игр", "Безопасность системы и UAC", "Административные общие ресурсы", "Доступ к удаленному рабочему столу", "Device Guard и параметры спекулятивного выполнения", "Файловая система и длинные пути", "Политики PowerShell и командной строки", "Служба телеметрии и запланированная задача", "Хеширование файлов и папок в контекстном меню", "Команда получения прав владельца"],
        ["es"] = ["Escritorio, barra de tareas y menú Inicio", "Comportamiento del Explorador de archivos", "Protector de pantalla", "Efectos visuales y respuesta del escritorio", "Comportamiento del ratón", "Asistente de concentración", "Privacidad y personalización", "Contenido recomendado y patrocinado", "Búsqueda de Windows e historial en la nube", "Comentarios y avisos de incorporación", "Notificaciones emergentes y de pantalla de bloqueo", "Juegos y Game Bar", "Símbolo del sistema y consola", "Funciones para desarrolladores", "Directivas del Explorador, barra de tareas e Inicio", "Noticias, fuentes y Copilot", "Contenido de consumidor y nube de Windows", "Directivas de Microsoft Edge", "Directivas de Windows Update y optimización de distribución", "Omisión de requisitos de instalación de Windows", "Hibernación, inicio rápido y plan de energía activo", "Plan de energía equilibrado", "Plan de alto rendimiento", "Plan de ahorro de energía", "Plan de máximo rendimiento", "Rendimiento del sistema y juegos", "Seguridad del sistema y UAC", "Recursos compartidos administrativos", "Acceso a Escritorio remoto", "Device Guard y ejecución especulativa", "Sistema de archivos y rutas largas", "Directivas de PowerShell y símbolo del sistema", "Servicio de telemetría y tarea programada", "Hash de archivos y carpetas en el menú contextual", "Tomar posesión desde el menú contextual"],
        ["fr"] = ["Bureau, barre des tâches et menu Démarrer", "Comportement de l’Explorateur de fichiers", "Écran de veille", "Effets visuels et réactivité du bureau", "Comportement de la souris", "Assistant de concentration", "Confidentialité et personnalisation", "Contenu recommandé et sponsorisé", "Recherche Windows et historique cloud", "Commentaires et invites de prise en main", "Notifications toast et écran de verrouillage", "Jeux et Game Bar", "Invite de commandes et console", "Fonctions de développement", "Stratégies Explorateur, barre des tâches et Démarrer", "Actualités, flux et Copilot", "Contenu consommateur et cloud Windows", "Stratégies Microsoft Edge", "Stratégies Windows Update et optimisation de la distribution", "Contournement des exigences d’installation Windows", "Veille prolongée, démarrage rapide et mode d’alimentation actif", "Mode d’alimentation équilibré", "Mode hautes performances", "Mode économie d’énergie", "Mode performances ultimes", "Performances système et jeux", "Sécurité système et UAC", "Partages de fichiers administratifs", "Accès Bureau à distance", "Device Guard et exécution spéculative", "Système de fichiers et chemins longs", "Stratégies PowerShell et invite de commandes", "Service de télémétrie et tâche planifiée", "Hachage de fichiers et dossiers dans le menu contextuel", "Prendre possession depuis le menu contextuel"],
        ["ar"] = ["سطح المكتب وشريط المهام وقائمة ابدأ", "سلوك مستكشف الملفات", "شاشة التوقف", "المؤثرات المرئية واستجابة سطح المكتب", "سلوك الماوس", "مساعد التركيز", "الخصوصية والتخصيص", "المحتوى المقترح والمدعوم", "بحث Windows والسجل السحابي", "الملاحظات ومطالبات الإعداد", "إشعارات الشعارات وشاشة القفل", "الألعاب وGame Bar", "موجه الأوامر ووحدة التحكم", "ميزات المطور", "نهج المستكشف وشريط المهام وابدأ", "الأخبار والموجزات وCopilot", "محتوى المستهلك والسحابة في Windows", "نهج Microsoft Edge", "نهج Windows Update وتحسين التسليم", "تجاوز متطلبات تثبيت Windows", "الإسبات وبدء التشغيل السريع وخطة الطاقة النشطة", "خطة الطاقة المتوازنة", "خطة الأداء العالي", "خطة توفير الطاقة", "خطة الأداء الأقصى", "أداء النظام والألعاب", "أمان النظام وUAC", "مشاركات الملفات الإدارية", "الوصول إلى سطح المكتب البعيد", "Device Guard وإعدادات التنفيذ التخميني", "نظام الملفات والمسارات الطويلة", "نهج PowerShell وموجه الأوامر", "خدمة القياس عن بعد والمهمة المجدولة", "تجزئة الملفات والمجلدات في قائمة السياق", "الحصول على الملكية من قائمة السياق"],
        ["pt-BR"] = ["Área de trabalho, barra de tarefas e menu Iniciar", "Comportamento do Explorador de Arquivos", "Proteção de tela", "Efeitos visuais e resposta da área de trabalho", "Comportamento do mouse", "Assistente de foco", "Privacidade e personalização", "Conteúdo recomendado e patrocinado", "Pesquisa do Windows e histórico na nuvem", "Comentários e avisos de introdução", "Notificações toast e da tela de bloqueio", "Jogos e Game Bar", "Prompt de Comando e console", "Recursos de desenvolvedor", "Políticas do Explorador, barra de tarefas e Iniciar", "Notícias, feeds e Copilot", "Conteúdo do consumidor e da nuvem do Windows", "Políticas do Microsoft Edge", "Políticas do Windows Update e otimização de entrega", "Ignorar requisitos de instalação do Windows", "Hibernação, inicialização rápida e plano de energia ativo", "Plano de energia equilibrado", "Plano de alto desempenho", "Plano de economia de energia", "Plano de desempenho máximo", "Desempenho do sistema e jogos", "Segurança do sistema e UAC", "Compartilhamentos administrativos", "Acesso à Área de Trabalho Remota", "Device Guard e execução especulativa", "Sistema de arquivos e caminhos longos", "Políticas do PowerShell e Prompt de Comando", "Serviço de telemetria e tarefa agendada", "Hash de arquivos e pastas no menu de contexto", "Assumir propriedade no menu de contexto"],
        ["ja"] = ["デスクトップ、タスクバー、スタート メニュー", "エクスプローラーの動作", "スクリーン セーバー", "視覚効果とデスクトップの応答性", "マウスの動作", "フォーカス アシスト", "プライバシーと個人設定", "おすすめとスポンサー コンテンツ", "Windows 検索とクラウド履歴", "フィードバックと初期設定の案内", "トーストとロック画面の通知", "ゲームと Game Bar", "コマンド プロンプトとコンソール", "開発者向け機能", "エクスプローラー、タスクバー、スタートのポリシー", "ニュース、フィード、Copilot", "Windows コンシューマーとクラウド コンテンツ", "Microsoft Edge ポリシー", "Windows Update と配信の最適化ポリシー", "Windows インストール要件の回避", "休止状態、高速スタートアップ、電源プラン", "バランス電源プラン", "高パフォーマンス電源プラン", "省電力電源プラン", "究極のパフォーマンス電源プラン", "システムとゲームのパフォーマンス", "システム セキュリティと UAC", "管理共有", "リモート デスクトップ アクセス", "Device Guard と投機的実行の設定", "ファイル システムと長いパス", "PowerShell とコマンド プロンプトのポリシー", "テレメトリ サービスとスケジュール タスク", "ファイルとフォルダーのハッシュ コンテキスト メニュー", "所有権取得コンテキスト メニュー"],
        ["de"] = ["Desktop, Taskleiste und Startmenü", "Verhalten des Datei-Explorers", "Bildschirmschoner", "Visuelle Effekte und Desktop-Reaktion", "Mausverhalten", "Fokus-Assistent", "Datenschutz und Personalisierung", "Empfohlene und gesponserte Inhalte", "Windows-Suche und Cloudverlauf", "Feedback und Einführungsaufforderungen", "Toast- und Sperrbildschirmbenachrichtigungen", "Spiele und Game Bar", "Eingabeaufforderung und Konsole", "Entwicklerfunktionen", "Explorer-, Taskleisten- und Start-Richtlinien", "Nachrichten, Feeds und Copilot", "Windows-Verbraucher- und Cloudinhalte", "Microsoft-Edge-Richtlinien", "Windows-Update- und Übermittlungsoptimierungsrichtlinien", "Umgehung der Windows-Installationsanforderungen", "Ruhezustand, Schnellstart und aktiver Energiesparplan", "Ausbalancierter Energiesparplan", "Höchstleistungs-Energiesparplan", "Energiesparplan", "Ultimative-Leistung-Energiesparplan", "System- und Spieleleistung", "Systemsicherheit und UAC", "Administrative Dateifreigaben", "Remotedesktopzugriff", "Device Guard und spekulative Ausführung", "Dateisystem und lange Pfade", "PowerShell- und Eingabeaufforderungsrichtlinien", "Telemetriedienst und geplante Aufgabe", "Datei- und Ordnerhashes im Kontextmenü", "Besitz übernehmen im Kontextmenü"]
    };
    private static readonly int RegistryGroupNameCount = ValidateRegistryGroupNames();

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> AdditionalDomains =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["zh-CN"] = Map(("Windows features", "Windows 功能"), ("Safety and recovery", "安全与恢复")), ["ru"] = Map(("Windows features", "Компоненты Windows"), ("Safety and recovery", "Безопасность и восстановление")),
            ["es"] = Map(("Windows features", "Características de Windows"), ("Safety and recovery", "Seguridad y recuperación")), ["fr"] = Map(("Windows features", "Fonctionnalités Windows"), ("Safety and recovery", "Sécurité et récupération")),
            ["ar"] = Map(("Windows features", "ميزات Windows"), ("Safety and recovery", "الأمان والاسترداد")), ["pt-BR"] = Map(("Windows features", "Recursos do Windows"), ("Safety and recovery", "Segurança e recuperação")),
            ["ja"] = Map(("Windows features", "Windows の機能"), ("Safety and recovery", "安全性と回復")), ["de"] = Map(("Windows features", "Windows-Features"), ("Safety and recovery", "Sicherheit und Wiederherstellung"))
        };

    public static string TaskName(string taskId, string fallback)
    {
        if (ConfigurableRegistrySettingCatalog.Find(taskId) is not null)
            return Localization.Get(taskId);
        _ = RegistryGroupNameCount;
        var groupIndex = Array.FindIndex(RegistryGroupTaskIds, id => id.Equals(taskId, StringComparison.OrdinalIgnoreCase));
        if (groupIndex >= 0 && RegistryGroupTaskNames.TryGetValue(Localization.CurrentCode, out var groupValues)) return groupValues[groupIndex];
        var index = Array.FindIndex(V23TaskIds, id => id.Equals(taskId, StringComparison.OrdinalIgnoreCase));
        if (index >= 0 && V23TaskNames.TryGetValue(Localization.CurrentCode, out var values)) return values[index];
        return Lookup(TaskNames, taskId, fallback);
    }
    public static string Domain(string domain)
    {
        if (domain == "Office and productivity") return Localization.Get("officeProductivity");
        if (domain == "Communication") return Localization.Get("communication");
        var index = Array.FindIndex(RegistryDomainNames, name => name.Equals(domain, StringComparison.OrdinalIgnoreCase));
        if (index >= 0 && RegistryDomains.TryGetValue(Localization.CurrentCode, out var values)) return values[index];
        var localized = Lookup(AdditionalDomains, domain, domain);
        return localized.Equals(domain, StringComparison.Ordinal) ? Lookup(Domains, domain, domain) : localized;
    }

    public static string Risk(RiskLevel risk) => Localization.Get(risk switch
    {
        RiskLevel.Standard => "standard",
        RiskLevel.Elevated => "elevated",
        _ => "high"
    });

    public static string Source(TaskSource source) => Localization.Get(source == TaskSource.BuiltIn ? "builtIn" : "controlledExtension");
    public static string State(TaskState state) => Localization.Get("state" + state);

    private static string Lookup(IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> catalogs, string key, string fallback) =>
        catalogs.TryGetValue(Localization.CurrentCode, out var values) && values.TryGetValue(key, out var value) ? value : fallback;

    private static IReadOnlyDictionary<string, string> Map(params (string Key, string Value)[] values) =>
        values.ToDictionary(item => item.Key, item => item.Value, StringComparer.OrdinalIgnoreCase);

    private static int ValidateRegistryGroupNames()
    {
        foreach (var (code, names) in RegistryGroupTaskNames)
            if (names.Length != RegistryGroupTaskIds.Length)
                throw new InvalidOperationException($"Registry group localization '{code}' has {names.Length} names; expected {RegistryGroupTaskIds.Length}.");
        return RegistryGroupTaskIds.Length;
    }
}
